---
- name: Group
  group:
    name: '{{ peertube__group }}'
    system: true

- name: User
  user:
    name: '{{ peertube__user }}'
    group: '{{ peertube__group }}'
    system: true
    create_home: false
