---
- name: Group
  group:
    name: '{{ peertube__group }}'
    system: true

- name: User
  user:
    name: '{{ peertube__user }}'
    group: '{{ peertube__group }}'
    system: true
    create_home: false

- name: Create directories
  file:
    state: directory
    path: '{{ item }}'
    mode: 'u=rwx,g=rx,o=rx'
    owner: '{{ peertube__user }}'
    group: '{{ peertube__group }}'
  with_items:
    - '{{ peertube__dir }}'
    - '{{ peertube__config_dir }}'
    - '{{ peertube__storage_dir }}'
    - '{{ peertube__versions_dir }}'
    - '{{ peertube__version_dir }}'

- name: Fetch archive
  get_url:
    url: '{{ peertube__archive_url }}'
    checksum: '{{ peertube__archive_checksum }}'
    dest: '{{ peertube__archive_file }}'
    mode: 'u=rw,g=r,o=r'
    owner: '{{ peertube__user }}'
    group: '{{ peertube__group }}'

- name: Extract archive
  unarchive:
    remote_src: true
    src: '{{ peertube__archive_file }}'
    dest: '{{ peertube__version_dir }}'
    owner: '{{ peertube__user }}'
    group: '{{ peertube__group }}'
    extra_opts:
      - '--strip-components=1'
